### ISSUE TITLE
Transparency with rogue bugs

### ISSUE THREAD

**Issue by paulvilla** [Choonster-WoW-AddOns/TargetNameplateIndicator#7]
Transparency out of range is a bug in rogues, it only happens to me with this class

![Screenshot_1](https://github.com/user-attachments/assets/f08b2c2e-683d-4284-b8a5-d40fcd290d1e)

**Comment by Choonster** [comment]
I'm not too sure what the issue you're having there is, but it seems to be working fine for me with those Plater settings on a Rogue.

Can you please try to reproduce this with version 1.56, which I've just released to fix the issues on 11.0.0? If you're still getting the issue, please provide some more details like what the issue is and what settings are needed to reproduce it.
